
#Chest title
chest-name: '&6Default Chest'

#Chest description
chest-lore: "Un coffre générique"

#Items
items:
  1:
    name: "&6First ITEM #1"
    lore:
      - "---------------------------"
      - "#1"
      - "---------------------------"
    material: Material.DIRT
    spawn_chance: 25%
  2:
    name: "&6Second Item #2"
    lore:
      - "---------------------------"
      - "#2"
      - "---------------------------"
    material: Material.DIORITE
    spawn_chance: 75%