name: LootChest
version: '${project.version}'
main: fr.nistro.lootchest.LootChest
api-version: 1.19
authors: [ Nistro ]
description: plugin de génération de coffre avec des items randoms
commands:
  lootchest:
    description: Give yourself a loot chest
    usage: '/lootchest'